"""empty message

Revision ID: 63d5f49e30ba
Revises: 
Create Date: 2019-01-09 10:16:24.643894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d5f49e30ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treespeciesvote', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treespeciesvote', 'updated')
    # ### end Alembic commands ###
