"""empty message

Revision ID: 7462c8dca62e
Revises: 63d5f49e30ba
Create Date: 2019-01-10 11:49:17.496152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7462c8dca62e'
down_revision = '63d5f49e30ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('latin_name', sa.String(length=60), nullable=True))
    op.drop_column('species', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('species', sa.Column('description', sa.VARCHAR(length=200), nullable=True))
    op.drop_column('species', 'latin_name')
    # ### end Alembic commands ###
