"""empty message

Revision ID: 9b5e7dd57915
Revises: 
Create Date: 2019-01-06 22:44:48.408387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5e7dd57915'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treelocation')
    op.drop_table('treelocationvote')
    op.add_column('tree', sa.Column('latitude', sa.Float(precision=12), nullable=True))
    op.add_column('tree', sa.Column('longitude', sa.Float(precision=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tree', 'longitude')
    op.drop_column('tree', 'latitude')
    op.create_table('treelocationvote',
    sa.Column('tree_location_vote_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('tree_location_id', sa.INTEGER(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tree_location_id'], ['treelocation.tree_location_id'], ),
    sa.PrimaryKeyConstraint('tree_location_vote_id')
    )
    op.create_table('treelocation',
    sa.Column('tree_location_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('tree_id', sa.INTEGER(), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tree_id'], ['tree.tree_id'], ),
    sa.PrimaryKeyConstraint('tree_location_id')
    )
    # ### end Alembic commands ###
