"""empty message

Revision ID: f08d26fb2a34
Revises: 9fe9820f68e6
Create Date: 2019-01-29 14:58:12.044720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08d26fb2a34'
down_revision = '9fe9820f68e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userplantimage')
    op.drop_table('userplant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userplant',
    sa.Column('user_plant_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=60), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('user_plant_id')
    )
    op.create_table('userplantimage',
    sa.Column('user_plant_image_id', sa.INTEGER(), nullable=False),
    sa.Column('user_plant_id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_plant_id'], ['userplant.user_plant_id'], ),
    sa.PrimaryKeyConstraint('user_plant_image_id')
    )
    # ### end Alembic commands ###
